import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import tasksRouter from "./tasks";
import kpisRouter from "./kpis";
import attendanceRouter from "./attendance";
import qualityRouter from "./quality";
import messagesRouter from "./messages";
import meetingsRouter from "./meetings";
import notificationsRouter from "./notifications";
import leaderboardRouter from "./leaderboard";
import storageRouter from "./storage";
import videosRouter from "./videos";
import framioRouter from "./frameio";
import eventsRouter from "./events";
import pushRouter from "./push";
import salariesRouter from "./salaries";
import schedulesRouter from "./schedules";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(eventsRouter);
router.use(pushRouter);
router.use(usersRouter);
router.use(tasksRouter);
router.use(kpisRouter);
router.use(attendanceRouter);
router.use(qualityRouter);
router.use(messagesRouter);
router.use(meetingsRouter);
router.use(notificationsRouter);
router.use(leaderboardRouter);
router.use(salariesRouter);
router.use(schedulesRouter);
router.use(storageRouter);
router.use(videosRouter);
router.use(framioRouter);

export default router;
